# Setup powerlevel9k/10k
export TERM="xterm-256color"
POWERLEVEL9K_MODE='nerdfont-complete'
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=""
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX=" "
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status root_indicator background_jobs asdf)

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

main_speckel=~/speckel

# Aliases
alias sb='"/Applications/Sublime Text.app/Contents/SharedSupport/bin/subl"'
alias ll='exa -Blh --git --time-style long-iso'
alias sz='source ~/.zshrc'
alias ta='tmux -CC a -t default || tmux -CC new -s default'
alias s='pushd $main_speckel'
alias dup='docker compose -f $main_speckel/docker/development/docker-compose.yml up -d'
alias dstop='docker compose -f $main_speckel/docker/development/docker-compose.yml stop'
alias start-resque-scheduler="(cd $main_speckel && BUNDLE_GEMFILE=$main_speckel/Gemfile nohup bundle exec rake environment resque:scheduler >>! $main_speckel/log/scheduler.log 2>&1 &)"
alias start-resque-worker="(cd $main_speckel && BUNDLE_GEMFILE=$main_speckel/Gemfile nohup bundle exec rake environment resque:work QUEUE='*' >>! $main_speckel/log/resque_worker.log 2>&1 &)"
alias stop-resque="ps -ef | egrep '[r]esque' | awk '{print $2}' | xargs kill -9"
alias flush-dns="sudo dscacheutil -flushcache; sudo killall -HUP mDNSResponder"

[ -f ~/.iterm2_shell_integration.zsh ] && source ~/.iterm2_shell_integration.zsh
[ -f /usr/local/bin/virtualenvwrapper.sh ] && source /usr/local/bin/virtualenvwrapper.sh
[ -f ~/.awskeys ] && source ~/.awskeys
[ -f /usr/local/opt/asdf/asdf.sh ] && source /usr/local/opt/asdf/asdf.sh
